### PR TITLE
Bugfix/signature

### PR DESCRIPTION
**Pull request by vekexasia**
Transaction signing was not working properly.

zeroPad function was not properly written and it was not zeropadding properly.

Besides fixing that and adding a couple of tests with manually crafted tx within ark-node, I added the ability to specify the `timestamp` field (optional) when creating a transaction.

This gives user the ability to specify its own timestamp nonce and makes testing possible.

### CODE REVIEW

**Comment by luciorubeens** [comment]
How can I reproduce?

**Comment by vekexasia** [comment]
Just sign a transaction without merging and try to post it to a devark node. It will refuse your tx.

**Comment by luciorubeens** [comment]
+5

**Comment by vekexasia** [comment]
Thank you!!

**Pull request merged**
